name: Filter White Wins PGN and Push

# Give workflow permission to push to the repo
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: 'Input PGN filename in repo'
        required: true
        default: 'wkoth.pgn'
      output_file:
        description: 'Filtered PGN filename to save'
        required: true
        default: 'wkoths.pgn'

jobs:
  filter_white:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # required for pushing

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install python-chess
      run: pip install chess

    - name: Run b.py to filter PGN
      run: |
        python -u b.py "${{ github.event.inputs.input_file }}" "${{ github.event.inputs.output_file }}"

    - name: Commit and Push Filtered PGN
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ${{ github.event.inputs.output_file }}
        git commit -m "Filtered White wins and draws: ${{ github.event.inputs.output_file }}" || echo "No changes to commit"
        git push 
